name: Предложение
description: Предложить улучшение UDMC
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какая проблема решается
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предлагаемое поведение
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
