package dev.udmc.sync;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * A server that starts without a project makes one for itself: an admin token, an Ed25519 pair for
 * signing manifests, and a pairing code that lets UDMC Control claim it. Nothing here is baked into
 * the JAR, so the same file serves every server and every player.
 *
 * <p>The code has no expiry. It lives in the configuration, so restarts do not change it and there
 * is no window to miss; it is spent the moment a panel pairs, and a reset issues a new one.
 */
public final class ServerIdentity {
    /** The token a configuration carries before anyone has set one. */
    public static final String UNSET_TOKEN = "change-me";
    /** Digits and letters that survive being read off a console and typed back in. */
    private static final String ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";
    private static final int GROUPS = 4, GROUP_SIZE = 4;
    private static final SecureRandom RANDOM = new SecureRandom();
    private static final String PAIRING_FILE = "udmc-pairing.txt";
    private static final Map<String, Window> ATTEMPTS = new LinkedHashMap<>();

    private ServerIdentity() {
    }

    /**
     * Fills in whatever this server is missing and keeps the pairing note on disk in step with it.
     * Safe to call on every start: a server that already has a project is left alone.
     *
     * @return true when the configuration changed and has been saved
     */
    public static boolean ensure(Path gameDir, UdmcConfig config) {
        boolean changed = false;

        if (config.resetPairing) {
            // Deliberate, and the only way back when a project was paired to the wrong panel: the
            // keys stay, so players keep trusting this server, but every device loses its access.
            config.resetPairing = false;
            config.adminToken = token();
            config.pairingCode = code();
            changed = true;
            // The registry that admitted those panels is bound to the old token. Set aside here,
            // with the reset that makes it stale, rather than left to refuse the whole admin API
            // at start-up because its binding no longer matches.
            try {
                Path registry = ManagedPaths.internal(gameDir, "admin-access.json");
                if (Files.exists(registry)) {
                    Files.move(registry, registry.resolveSibling("admin-access." + System.currentTimeMillis() + ".bak.json"));
                }
            } catch (IOException error) {
                UdmcSync.LOGGER.error("UDMC could not set the administrator registry aside after the pairing reset", error);
            }
            UdmcSync.LOGGER.warn("UDMC pairing was reset. Previously paired panels no longer have access.");
        }

        // The signing pair is what makes this a project, so creating it is what needs claiming.
        if (config.manifestPublicKey.isBlank() || config.manifestPrivateKey.isBlank()) {
            KeyPair pair = generateKeys();
            config.manifestPublicKey = encode(pair.getPublic().getEncoded());
            config.manifestPrivateKey = encode(pair.getPrivate().getEncoded());
            config.requireSignedManifest = true;
            config.pairingCode = code();
            changed = true;
        }
        if (config.adminToken == null || config.adminToken.isBlank() || UNSET_TOKEN.equals(config.adminToken)) {
            config.adminToken = token();
            changed = true;
        }
        if (standDownAfterProtocolChange(config)) changed = true;

        if (changed) config.save(gameDir);
        writeNote(gameDir, config);
        return changed;
    }

    /**
     * Keeps a protocol change from locking a server's own players out. Clients from before a
     * change cannot answer the new question, and turning them away on that silence would shut
     * the door on everybody the moment the agent is updated. The rule stands down once; the
     * administrator switches it back on after handing out the new client.
     *
     * <p>This lives here rather than beside the settings file because it has to run on every
     * server, including one that was never generated by Control and has nothing baked in.
     */
    private static boolean standDownAfterProtocolChange(UdmcConfig config) {
        if (config.verifyProtocol >= AgentLoginProtocol.PROTOCOL) return false;
        if (config.requireClientAgent) {
            UdmcSync.LOGGER.warn("UDMC changed what it asks a joining client, and clients from before this update cannot"
                + " answer. Login is no longer restricted: hand out the new client mod, then switch \"require the UDMC"
                + " client\" back on in Control.");
        }
        config.requireClientAgent = false;
        config.verifyProtocol = AgentLoginProtocol.PROTOCOL;
        return true;
    }

    /** True while nobody has paired with this server, which is when the code still works. */
    public static boolean unpaired(UdmcConfig config) {
        return config.pairingCode != null && !config.pairingCode.isBlank();
    }

    /**
     * Spends the pairing code. Called once a panel has proved it knows the code; from here on the
     * server is claimed and the note on disk is gone.
     */
    public static void paired(Path gameDir, UdmcConfig config) {
        config.pairingCode = "";
        config.save(gameDir);
        writeNote(gameDir, config);
        UdmcSync.LOGGER.info("UDMC is now paired with a panel. The pairing code has been used up.");
    }

    /** Where the pairing note lives: beside the configuration, which is never served over HTTP. */
    public static Path notePath(Path gameDir) {
        return gameDir.resolve("config").resolve(PAIRING_FILE);
    }

    /**
     * Keeps the code where a server owner can actually reach it. Hosting panels differ wildly in
     * what they expose, so it goes to the log and to a file: whoever has a console has one, whoever
     * has only a file manager has the other.
     */
    private static void writeNote(Path gameDir, UdmcConfig config) {
        Path note = notePath(gameDir);
        try {
            if (!unpaired(config)) {
                Files.deleteIfExists(note);
                return;
            }
            Files.createDirectories(note.getParent());
            Files.writeString(note, note(config.pairingCode), StandardCharsets.UTF_8);
        } catch (IOException error) {
            // The console still carries the code, so this is worth a warning and nothing more.
            UdmcSync.LOGGER.warn("UDMC could not write {}: {}", note, error.toString());
        }
        UdmcSync.LOGGER.info("UDMC is waiting to be paired. Pairing code: {}", config.pairingCode);
        UdmcSync.LOGGER.info("Enter it in UDMC Control, or find it again in {}", note);
    }

    private static String note(String code) {
        return """
            UDMC pairing code / код привязки UDMC

                %s

            Enter this code in UDMC Control to claim this server.
            Введите этот код в UDMC Control, чтобы привязать сервер.

            The code does not expire and survives restarts. It stops working once the server is
            paired, and this file disappears with it.
            Код не истекает и переживает перезапуски. Он перестаёт работать сразу после привязки,
            и этот файл исчезает вместе с ним.
            """.formatted(code);
    }

    private static KeyPair generateKeys() {
        try {
            return KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        } catch (Exception error) {
            throw new IllegalStateException("This Java cannot create Ed25519 keys", error);
        }
    }

    private static String encode(byte[] value) {
        return Base64.getEncoder().encodeToString(value);
    }

    /** 32 random bytes as hex, matching what Control has always issued. */
    private static String token() {
        byte[] value = new byte[32];
        RANDOM.nextBytes(value);
        StringBuilder text = new StringBuilder(value.length * 2);
        for (byte b : value) text.append("%02x".formatted(b));
        return text.toString();
    }

    /** Four groups of four, from an alphabet without characters that read as one another. */
    private static String code() {
        StringBuilder text = new StringBuilder(GROUPS * GROUP_SIZE + GROUPS - 1);
        for (int group = 0; group < GROUPS; group++) {
            if (group > 0) text.append('-');
            for (int index = 0; index < GROUP_SIZE; index++) {
                text.append(ALPHABET.charAt(RANDOM.nextInt(ALPHABET.length())));
            }
        }
        return text.toString();
    }

    /**
     * Hands the project over to a panel that knows the code, and spends the code doing it.
     *
     * <p>The private signing key is not part of this: the server signs its own manifests and never
     * needs to give that away. A backup copy is a separate, deliberate request over the admin
     * channel, so the one secret that could impersonate this project does not travel by default.
     */
    public static synchronized Map<String, Object> claim(Path gameDir, UdmcConfig config, String submitted, String ip) {
        return claim(gameDir, config, submitted, ip, null);
    }

    /**
     * Claims the server, optionally putting a saved project back in place of the one it made for
     * itself. Restoring is part of claiming rather than a request of its own: it is only ever
     * safe on a server nobody has claimed yet, and that is exactly what the code proves.
     */
    public static synchronized Map<String, Object> claim(Path gameDir, UdmcConfig config, String submitted, String ip,
                                                         Map<String, Object> project) {
        if (!unpaired(config)) {
            throw new ApiException(409, "PAIRING_ALREADY_DONE",
                "This server is already paired. Reset pairing on the server to pair it again.");
        }
        rateLimit(ip);
        if (!MessageDigest.isEqual(normalize(config.pairingCode).getBytes(StandardCharsets.UTF_8),
                normalize(submitted).getBytes(StandardCharsets.UTF_8))) {
            UdmcSync.LOGGER.warn("UDMC refused a pairing attempt from {}: wrong code.", ip);
            throw new ApiException(403, "PAIRING_CODE_INVALID", "That pairing code does not match this server.");
        }

        if (project != null) restore(config, project);

        Map<String, Object> claimed = new LinkedHashMap<>();
        claimed.put("packId", config.packId);
        claimed.put("packName", config.packName);
        claimed.put("adminToken", config.adminToken);
        claimed.put("manifestPublicKey", config.manifestPublicKey);
        claimed.put("fingerprint", fingerprint(config.manifestPublicKey));
        claimed.put("minecraftVersion", config.minecraftVersion);
        claimed.put("loaderType", config.loaderType);
        claimed.put("loaderVersion", config.loaderVersion);
        claimed.put("apiPort", config.apiPort);
        claimed.put("agentVersion", PlatformDefaults.get("agentVersion"));
        paired(gameDir, config);
        UdmcSync.LOGGER.info("UDMC was paired from {}.", ip);
        return claimed;
    }

    /**
     * The whole project, including the key that signs for it. A server holds the only copy of
     * that key, so losing the machine would mean losing the project and every player's trust in
     * it: they would have to accept a new key from a server claiming the same name.
     *
     * <p>Deliberate and owner-only. This is the one request that puts the signing key on the
     * network, which is why it is not part of pairing and not something a panel does by itself.
     */
    public static Map<String, Object> backup(UdmcConfig config) {
        Map<String, Object> project = new LinkedHashMap<>();
        project.put("format", "udmc-project-backup-1");
        project.put("packId", config.packId);
        project.put("packName", config.packName);
        project.put("adminToken", config.adminToken);
        project.put("manifestPublicKey", config.manifestPublicKey);
        project.put("manifestPrivateKey", config.manifestPrivateKey);
        project.put("fingerprint", fingerprint(config.manifestPublicKey));
        return project;
    }

    /**
     * Puts a saved project back onto a server that has just been set up. The pairing code is
     * what authorises it: only whoever controls the new server can spend it, and the server has
     * nothing to lose yet - it has just invented an identity nobody has ever trusted.
     */
    private static void restore(UdmcConfig config, Map<String, Object> project) {
        String packId = text(project, "packId"), token = text(project, "adminToken");
        String publicKey = text(project, "manifestPublicKey"), privateKey = text(project, "manifestPrivateKey");
        if (!packId.matches("[A-Za-z0-9_-]{1,64}") || !token.matches("[0-9a-f]{64}")) {
            throw new ApiException(400, "PROJECT_BACKUP_INVALID", "This is not a UDMC project backup.");
        }
        // The pair has to actually be a pair. A backup with mismatched keys would produce a
        // server that signs with one key and tells players to trust another - every download
        // failing a signature check, with nothing on screen to explain why.
        try {
            byte[] probe = "udmc-project-restore".getBytes(StandardCharsets.UTF_8);
            ManifestSecurity.verify(probe, ManifestSecurity.sign(probe, privateKey), publicKey);
        } catch (Exception error) {
            throw new ApiException(400, "PROJECT_BACKUP_KEYS_MISMATCH", "The keys in this backup do not belong together.");
        }
        config.packId = packId;
        config.packName = text(project, "packName").isEmpty() ? packId : text(project, "packName");
        config.adminToken = token;
        config.manifestPublicKey = publicKey;
        config.manifestPrivateKey = privateKey;
        config.requireSignedManifest = true;
        UdmcSync.LOGGER.warn("UDMC restored project {} from a backup. Players who trusted this project keep trusting it.", packId);
    }

    private static String text(Map<String, Object> value, String key) {
        Object result = value == null ? null : value.get(key);
        return result instanceof String string ? string.trim() : "";
    }

    /** What players see to tell one project from another: SHA-256 of the public key, in hex. */
    public static String fingerprint(String publicKey) {
        try {
            byte[] hash = MessageDigest.getInstance("SHA-256").digest(Base64.getDecoder().decode(publicKey));
            StringBuilder text = new StringBuilder(hash.length * 2);
            for (byte b : hash) text.append("%02x".formatted(b));
            return text.toString();
        } catch (Exception error) {
            return "";
        }
    }

    /**
     * Read off a console and typed back in, a code loses its dashes and its case. None of that
     * changes which code it is, so neither should it change whether it works.
     */
    private static String normalize(String code) {
        return code == null ? "" : code.trim().toUpperCase(Locale.ROOT).replace("-", "").replace(" ", "");
    }

    /** 80 bits of code is not guessable, but a server should not help anyone try. */
    private static void rateLimit(String ip) {
        long now = System.currentTimeMillis();
        ATTEMPTS.entrySet().removeIf(entry -> entry.getValue().until <= now);
        if (!ATTEMPTS.containsKey(ip) && ATTEMPTS.size() >= 2048) {
            throw new ApiException(429, "PAIRING_RATE_LIMIT", "Too many pairing attempts. Wait one minute.");
        }
        Window window = ATTEMPTS.computeIfAbsent(ip, ignored -> new Window(now + 60_000));
        if (++window.count > 10) {
            throw new ApiException(429, "PAIRING_RATE_LIMIT", "Too many pairing attempts. Wait one minute.");
        }
    }

    private static final class Window {
        final long until;
        int count;

        Window(long until) {
            this.until = until;
        }
    }
}
