package dev.udmc.sync;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class UdmcConfig {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public String serverUrl = "http://127.0.0.1:3077";
    public String apiHost = "0.0.0.0";
    public int apiPort = 3077;
    public String adminToken = "change-me";
    public boolean clientSyncOnStart = true;
    public String packId = "udmc-main";
    public String packName = "UDMC Main Modpack";
    public String packVersion = "0.1.0";
    public String minecraftVersion = PlatformDefaults.get("minecraft");
    public String loaderType = LoaderPlatform.TYPE;
    public String loaderVersion = PlatformDefaults.get("loaderVersion");
    public String languageLoaderVersion = PlatformDefaults.get("languageLoaderVersion");
    public volatile boolean allowRemotePowerActions = false;
    /** Public game address (host[:port]) that players should join; empty when the admin has not set one. */
    public volatile String gameAddress = "";
    public String role = "universal";
    public String bootstrapId = "";
    public String manifestPublicKey = "";
    public String manifestPrivateKey = "";
    public boolean requireSignedManifest = false;
    public boolean allowInsecureHttp = false;
    public volatile boolean requireClientAgent = false;
    /** Whether this run took its settings from a JAR generated by Control. Never stored. */
    public transient boolean fromBootstrap;

    /** Validates an optional player-facing game address; returns the trimmed value or "" to clear it. */
    public static String normalizeGameAddress(String value) {
        String address = value == null ? "" : value.trim();
        if (address.isEmpty()) return "";
        if (address.length() > 260
            || address.chars().anyMatch(c -> c <= ' ' || c == 127 || "/\\@#?\"'".indexOf(c) >= 0)) {
            throw new IllegalArgumentException("Invalid game address");
        }
        String host = address;
        String port = null;
        if (address.startsWith("[")) {
            int end = address.indexOf(']');
            if (end < 2) throw new IllegalArgumentException("Invalid game address");
            host = address.substring(1, end);
            String rest = address.substring(end + 1);
            if (!rest.isEmpty()) {
                if (!rest.startsWith(":")) throw new IllegalArgumentException("Invalid game address");
                port = rest.substring(1);
            }
            if (!host.matches("[0-9A-Fa-f:]+")) throw new IllegalArgumentException("Invalid game address");
        } else {
            int sep = address.lastIndexOf(':');
            if (address.indexOf(':') != sep) throw new IllegalArgumentException("Invalid game address");
            if (sep >= 0) {
                host = address.substring(0, sep);
                port = address.substring(sep + 1);
            }
            if (host.isEmpty() || !host.matches("[A-Za-z0-9.-]+")) {
                throw new IllegalArgumentException("Invalid game address");
            }
        }
        if (port != null && (!port.matches("\\d{1,5}") || Integer.parseInt(port) < 1 || Integer.parseInt(port) > 65535)) {
            throw new IllegalArgumentException("Invalid game address");
        }
        return address;
    }

    public void applyRuntimeEnvironment() {
        minecraftVersion = LoaderPlatform.version("minecraft", minecraftVersion);
        loaderType = LoaderPlatform.TYPE;
        loaderVersion = LoaderPlatform.version(LoaderPlatform.MOD_ID, loaderVersion);
        languageLoaderVersion = LoaderPlatform.version("@fml", languageLoaderVersion);
    }

    public static UdmcConfig load(Path gameDir) {
        Path configPath = configPath(gameDir);

        try {
            if (Files.exists(configPath)) {
                UdmcConfig stored;
                // Read the file and let go of it before applying the bootstrap: a JAR from a
                // newer generation rewrites this very file, and Windows refuses to replace a
                // file while a handle to it is still open - the game crashed on startup.
                try (Reader reader = Files.newBufferedReader(configPath)) {
                    stored = GSON.fromJson(reader, UdmcConfig.class);
                }
                return applyBootstrap(gameDir, stored == null ? new UdmcConfig() : stored);
            }

            UdmcConfig config = applyBootstrap(gameDir, new UdmcConfig());
            config.save(gameDir);
            return config;
        } catch (IOException error) {
            throw new IllegalStateException("Cannot load UDMC config: " + configPath, error);
        }
    }

    private static UdmcConfig applyBootstrap(Path gameDir, UdmcConfig config) throws IOException {
        try (var input = UdmcConfig.class.getResourceAsStream("/udmc-bootstrap.json")) {
            // A JAR built from source carries no project. It is not a file players install,
            // and the caller has to know: keeping whatever the previous config said is how a
            // client ends up answering for a project the server has never heard of.
            if (input == null) return config;
            UdmcConfig embedded = GSON.fromJson(new InputStreamReader(input, StandardCharsets.UTF_8), UdmcConfig.class);
            if (embedded == null || embedded.manifestPublicKey.isBlank() || embedded.bootstrapId.isBlank()) {
                throw new IOException("Invalid UDMC bootstrap configuration");
            }
            boolean elsewhere = !config.manifestPublicKey.isBlank() && (!config.manifestPublicKey.equals(embedded.manifestPublicKey)
                || !config.packId.equals(embedded.packId) || !config.role.equals(embedded.role));
            // A server config holds this project's secrets, so a foreign server JAR is
            // refused. A client config holds nothing worth keeping: the installed JAR
            // decides which project the client belongs to, which is the whole point of
            // handing a player a new file. The previous settings are kept beside it.
            if (elsewhere && "server".equals(embedded.role)) {
                throw new IOException("This UDMC server JAR belongs to a different project or role. Back up and remove config/udmc-sync.json before switching projects.");
            }
            if (elsewhere) {
                Path kept = keepPrevious(gameDir);
                UdmcSync.LOGGER.warn("UDMC client settings belonged to another project and were replaced by the installed JAR. Previous settings: {}", kept);
                config = new UdmcConfig();
            }
            config.fromBootstrap = true;
            if (!embedded.bootstrapId.equals(config.bootstrapId)) {
                config.serverUrl = embedded.serverUrl;
                config.apiHost = embedded.apiHost;
                config.apiPort = embedded.apiPort;
                config.adminToken = "server".equals(embedded.role) ? embedded.adminToken : "";
                config.manifestPrivateKey = "server".equals(embedded.role) ? embedded.manifestPrivateKey : "";
                config.manifestPublicKey = embedded.manifestPublicKey;
                config.requireSignedManifest = true;
                config.allowInsecureHttp = embedded.allowInsecureHttp;
                config.packId = embedded.packId;
                config.packName = embedded.packName;
                config.role = embedded.role;
                config.bootstrapId = embedded.bootstrapId;
                config.save(gameDir);
            }
            // A generated client cannot be downgraded to unsigned mode through an old config.
            config.requireSignedManifest = true;
            return config;
        }
    }

    public void save(Path gameDir) {
        Path configPath = configPath(gameDir);

        try {
            Files.createDirectories(configPath.getParent());
            if (Files.isSymbolicLink(configPath) || Files.isSymbolicLink(configPath.getParent())) throw new IOException("UDMC configuration must not be a symbolic link");
            Path temporary = Files.createTempFile(configPath.getParent(), "udmc-config-", ".tmp");
            try {
            try (Writer writer = Files.newBufferedWriter(temporary)) {
                GSON.toJson(this, writer);
            }
            try { Files.move(temporary, configPath, java.nio.file.StandardCopyOption.ATOMIC_MOVE, java.nio.file.StandardCopyOption.REPLACE_EXISTING); }
            catch (java.nio.file.AtomicMoveNotSupportedException error) { Files.move(temporary, configPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING); }
            } finally { Files.deleteIfExists(temporary); }
        } catch (IOException error) {
            throw new IllegalStateException("Cannot save UDMC config: " + configPath, error);
        }
    }

    /** Keeps the replaced settings beside the new ones instead of losing them silently. */
    private static Path keepPrevious(Path gameDir) throws IOException {
        Path from = configPath(gameDir), kept = from.resolveSibling("udmc-sync-previous.json");
        Files.copy(from, kept, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        return kept;
    }

    private static Path configPath(Path gameDir) {
        return gameDir.resolve("config").resolve("udmc-sync.json");
    }

}
